Agregar apellido al formulario de registro
marcelofarias/escuela-js pull request #29
Opened 2021-11-26 14:10 UTC by leandrotomassini

Un pull request de ejemplo.

2021-11-26 14:25 UTC, closed without merging

2021-11-26 14:26 UTC, leandrotomassini commented
Listo.

2022-04-22 11:37 UTC, deiviiss requested changes
CodeStreaam

2022-04-24 18:40 UTC, Danie113 commented on curso-frontend-developer/registro/registro.html
>          <input class="input" type="password" placeholder="Contraseña">
Hola

2022-06-09 02:19 UTC, kvaldivia-creator commented
Debe de decir terminos y condiciones

```
uso
```
								
[curso-frontend-developer/registro/registro.html](https://github.com/marcelofarias/escuela-js/blob/b9618c490cc2727761be54c91df5eae936eb89da/curso-frontend-developer/registro/registro.html#L32) (Line 32)