Agregar apellido al formulario de registro
marcelofarias/escuela-js pull request #5
Opened 2020-10-21 20:06 UTC by marcelofarias

2020-10-21 20:07 UTC, gustavo-cerati-codestream requested changes

2020-10-21 20:07 UTC, gustavo-cerati-codestream commented on curso-frontend-developer/registro/registro.html
> +        <input class="input" type="text" placeholder="Apellido">
Estos campos ahora son requeridos

2020-12-20 04:42 UTC, IsraelOxlaj commented on curso-frontend-developer/registro/registro.html
>          <input class="input" type="password" placeholder="Contraseña">
hacer que este campo sea requerido!

2020-12-26 06:48 UTC, lesterpaz99 commented on curso-frontend-developer/registro/registro.html
> +        <input class="input" type="text" placeholder="Apellido">
Comentario de practica en el curso de desarrollo moderno con CodeStream :grinning:

2020-12-26 06:52 UTC, lesterpaz99 requested changes
Ignorar, curso de desarrollo moderno con codestream.

2021-01-06 13:41 UTC, tferreyraw commented
ignore, comentario del curso de desarrollo moderno en codestream

2021-01-06 13:57 UTC, tferreyraw requested changes
el salto de linea no es necesario

2021-04-04 14:15 UTC, David-prog-wed approved these changes

2021-04-04 14:16 UTC, David-prog-wed commented
por supuesto

2026-04-17 09:33 UTC, closed without merging