PE-7 Agregar fecha de nacimiento al formulario de registro
marcelofarias/escuela-js pull request #9
Opened 2020-11-23 22:38 UTC by marcelofarias

**This PR Addresses:**  
[PE-7 Agregar fecha de nacimiento al formulario de registro](https://teamcodestream.atlassian.net/browse/PE-7)

2020-11-23 22:39 UTC, gustavo-cerati-codestream commented on curso-frontend-developer/registro/registro.html
> +        <input class="input" type="text" placeholder="Fecha de nacimiento">
Estes campos ahora son requeridos

2020-12-02 04:51 UTC, EmmaIsWorking commented
Recomendado el espacio

```
</html>
```
								
[curso-frontend-developer/registro/registro.html](https://github.com/marcelofarias/escuela-js/blob/daa2b7f70e460175239252a8c478dccac75cda7f/curso-frontend-developer/registro/registro.html#L37) (Line 37)

2020-12-02 04:54 UTC, EmmaIsWorking commented
Este es un comentario de ejemplo del curso de Flujo de Desarrollo Moderno CodeStream

```
  <footer class="footer">

```
								
[curso-frontend-developer/registro/registro.html](https://github.com/marcelofarias/escuela-js/blob/daa2b7f70e460175239252a8c478dccac75cda7f/curso-frontend-developer/registro/registro.html#L31) (Line 31)

2020-12-15 19:56 UTC, ja54312 requested changes
Comentario de Prubea del Curso de codestream

2021-02-17 22:00 UTC, JosemariaA reviewed
dsadsad

2021-04-10 19:08 UTC, onedrako commented on curso-frontend-developer/registro/registro.html
>          <input class="input" type="text" placeholder="Correo">
Coemnt

2021-05-03 05:35 UTC, Edikmar98 commented on curso-frontend-developer/registro/registro.html
>          <input class="input" type="text" placeholder="Nombre">
Prueba

2021-05-03 05:39 UTC, Edikmar98 requested changes
Prueba de review

2026-04-17 09:32 UTC, merged